/**
 * Threat Incident Report Exporter
 * Generates JSON, Markdown, and Print-ready security triage summaries.
 */

export class ReportExporter {
    static exportAsJson(report) {
        if (!report) return;
        const jsonStr = JSON.stringify(report, null, 2);
        const blob = new Blob([jsonStr], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `PhishGuard_Report_${report.id || 'analysis'}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    static exportAsMarkdown(report) {
        if (!report) return;

        const indicatorsList = (report.indicators || [])
            .map(i => `- **[${i.severity.toUpperCase()}] ${i.title}**: ${i.description}`)
            .join('\n');

        const whyList = (report.whyReasons || [])
            .map(w => `- [${w.severity.toUpperCase()}] ${w.title}`)
            .join('\n');

        const md = `# PHISHGUARD THREAT ANALYSIS REPORT
**Report ID:** \`${report.id}\`  
**Generated:** ${report.timestamp}  
**Artifact Type:** ${report.artifactType.toUpperCase()}  
**Analysis Engine:** ${report.engineInfo?.aiEngine || 'Deterministic Heuristic'}

---

## 1. Executive Threat Verdict

* **Verdict:** **${report.verdict}**
* **Composite Risk Index:** \`${report.riskScore} / 100\`
* **Confidence Level:** ${report.confidence}

### Summary
${report.summary}

### Action Protocol / Mitigation Guidance
> **${report.recommendation}**

---

## 2. Key Findings ("Why?")
${whyList || 'No suspicious factors identified.'}

---

## 3. Detailed Indicators of Compromise (IOCs)
${indicatorsList || 'No active threat indicators detected.'}

---

## 4. Target Artifact Payload
\`\`\`text
${report.input}
\`\`\`

---
*Report generated by PhishGuard Threat Intelligence Workbench (Autonomous Client-Side & AI Hybrid Architecture).*
`;

        const blob = new Blob([md], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `PhishGuard_Report_${report.id || 'analysis'}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    static printReport() {
        window.print();
    }
}

